import { useState, useEffect } from 'react'

export function useData() {
  const [entries, setEntries] = useState([])
  const [metadata, setMetadata] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    async function load() {
      try {
        const base = import.meta.env.BASE_URL || '/'
        const res = await fetch(`${base}data/unified_index.json`)
        if (!res.ok) throw new Error(`HTTP ${res.status}. Make sure the data files have been generated by running the fetch scripts.`)
        const data = await res.json()
        let allEntries = data.entries || []
        const meta = data.metadata || {}

        if (meta.split) {
          try {
            const cveRes = await fetch(`${base}data/cves_index.json`)
            if (cveRes.ok) {
              const cveData = await cveRes.json()
              allEntries = [...allEntries, ...(cveData.entries || [])]
            }
          } catch {
            // CVE index optional
          }
        }

        setEntries(allEntries)
        setMetadata(meta)
      } catch (err) {
        setError(err.message)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  return { entries, metadata, loading, error }
}
