import { useState, useEffect, useMemo, useCallback } from 'react'
import { useData } from './hooks/useData.js'
import { useSearch } from './hooks/useSearch.js'
import SearchBar from './components/SearchBar.jsx'
import FilterPills from './components/FilterPills.jsx'
import StatsBar from './components/StatsBar.jsx'
import EntryCard from './components/EntryCard.jsx'
import DetailPanel from './components/DetailPanel.jsx'

const PAGE_SIZE = 60

function SkeletonCard() {
  return (
    <div className="bg-gray-800/60 border border-gray-700 rounded-xl p-4 animate-pulse">
      <div className="flex gap-2 mb-3">
        <div className="h-5 w-16 bg-gray-700 rounded-full" />
      </div>
      <div className="h-3 w-24 bg-gray-700 rounded mb-2" />
      <div className="h-4 w-3/4 bg-gray-700 rounded mb-3" />
      <div className="h-3 bg-gray-700/60 rounded mb-1.5" />
      <div className="h-3 bg-gray-700/60 rounded w-5/6" />
    </div>
  )
}

// Sync query/source filters with URL params
function useUrlSync(query, setQuery, activeSources, setActiveSources) {
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const q = params.get('q') || ''
    const s = params.get('sources') ? params.get('sources').split(',').filter(Boolean) : []
    if (q) setQuery(q)
    if (s.length) setActiveSources(s)
  }, [])

  useEffect(() => {
    const params = new URLSearchParams()
    if (query) params.set('q', query)
    if (activeSources.length) params.set('sources', activeSources.join(','))
    const str = params.toString()
    const newUrl = str ? `${window.location.pathname}?${str}` : window.location.pathname
    window.history.replaceState(null, '', newUrl)
  }, [query, activeSources])
}

export default function App() {
  const { entries, metadata, loading, error } = useData()
  const [activeSources, setActiveSources] = useState([])
  const [cvssFilter, setCvssFilter] = useState(null)
  const { query, setQuery, results } = useSearch(entries, activeSources, cvssFilter)
  const [selected, setSelected] = useState(null)
  const [page, setPage] = useState(1)

  useUrlSync(query, setQuery, activeSources, setActiveSources)

  // Reset page when results change
  useEffect(() => { setPage(1) }, [query, activeSources, cvssFilter])

  const entryMap = useMemo(() => {
    const m = {}
    for (const e of entries) m[e.id] = e
    return m
  }, [entries])

  function toggleSource(source) {
    setActiveSources(prev =>
      prev.includes(source) ? prev.filter(s => s !== source) : [...prev, source]
    )
  }

  const visible = results.slice(0, page * PAGE_SIZE)
  const hasMore = results.length > visible.length

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b border-gray-800 bg-gray-900/80 backdrop-blur-sm sticky top-0 z-20">
        <div className="max-w-screen-xl mx-auto px-4 py-3 flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-3">
            <span className="text-xl font-bold text-white tracking-tight">ThreatBase</span>
            {metadata && (
              <span className="text-sm text-gray-500 hidden sm:block">
                {metadata.total?.toLocaleString()} entries
              </span>
            )}
          </div>
          {metadata?.generated_at && (
            <span className="text-xs text-gray-600">
              Updated {new Date(metadata.generated_at).toLocaleDateString()}
            </span>
          )}
        </div>
      </header>

      <main className="flex-1 max-w-screen-xl mx-auto w-full px-4 py-6 space-y-5">
        {/* Stats bar */}
        <StatsBar metadata={metadata} activeSources={activeSources} onToggleSource={toggleSource} />

        {/* Search */}
        <SearchBar query={query} onChange={setQuery} />

        {/* Filters */}
        <FilterPills
          activeSources={activeSources}
          onToggleSource={toggleSource}
          cvssFilter={cvssFilter}
          onCvssFilter={setCvssFilter}
        />

        {/* Status */}
        {!loading && !error && (
          <div className="text-xs text-gray-500">
            {query
              ? `${results.length.toLocaleString()} results for "${query}"`
              : `Showing recently updated — ${results.length.toLocaleString()} entries`}
            {(activeSources.length > 0 || cvssFilter) && ' (filtered)'}
          </div>
        )}

        {error && (
          <div className="bg-red-900/30 border border-red-700 rounded-xl p-4 text-red-300 text-sm">
            Failed to load data: {error}. Make sure the data files have been generated by running the fetch scripts.
          </div>
        )}

        {/* Results grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {loading
            ? Array.from({ length: 12 }).map((_, i) => <SkeletonCard key={i} />)
            : visible.map(entry => (
                <EntryCard
                  key={entry.id}
                  entry={entry}
                  onClick={setSelected}
                />
              ))
          }
        </div>

        {/* No results */}
        {!loading && !error && results.length === 0 && query && (
          <div className="text-center py-16">
            <div className="text-4xl mb-3">🔍</div>
            <p className="text-gray-400 mb-1">No results for <strong>"{query}"</strong></p>
            <p className="text-gray-600 text-sm">Try a shorter query, remove filters, or use source:ATT&CK / source:CVE prefixes</p>
          </div>
        )}

        {/* Load more */}
        {hasMore && (
          <div className="text-center pt-4">
            <button
              onClick={() => setPage(p => p + 1)}
              className="px-6 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-600 rounded-lg text-sm text-gray-300 transition-colors"
            >
              Load more ({results.length - visible.length} remaining)
            </button>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 py-4 px-4 text-center">
        <LastRunStatus />
        <p className="text-xs text-gray-700 mt-1">
          Data: <a href="https://attack.mitre.org" target="_blank" rel="noopener noreferrer" className="hover:text-gray-500">ATT&CK</a>
          {' · '}<a href="https://d3fend.mitre.org" target="_blank" rel="noopener noreferrer" className="hover:text-gray-500">D3FEND</a>
          {' · '}<a href="https://nvd.nist.gov" target="_blank" rel="noopener noreferrer" className="hover:text-gray-500">NVD/CVE</a>
          {' · '}<a href="https://cwe.mitre.org" target="_blank" rel="noopener noreferrer" className="hover:text-gray-500">CWE</a>
          {' · '}<a href="https://github.com/mitre/SPARTA" target="_blank" rel="noopener noreferrer" className="hover:text-gray-500">SPARTA</a>
          {' · '}<a href="https://github.com/esaSPACEops/SHIELD" target="_blank" rel="noopener noreferrer" className="hover:text-gray-500">ESA SHIELD</a>
          {' · MIT License'}
        </p>
      </footer>

      {/* Detail panel */}
      {selected && (
        <DetailPanel
          entry={selected}
          entryMap={entryMap}
          onClose={() => setSelected(null)}
          onSelect={setSelected}
        />
      )}
    </div>
  )
}

function LastRunStatus() {
  const [status, setStatus] = useState(null)
  useEffect(() => {
    const base = import.meta.env.BASE_URL || '/'
    fetch(`${base}data/last_run.json`)
      .then(r => r.ok ? r.json() : null)
      .then(d => d && setStatus(d))
      .catch(() => {})
  }, [])

  if (!status) return null

  const errors = Object.entries(status)
    .filter(([k, v]) => k !== '_generated_at' && v?.error)
    .map(([k]) => k)

  if (errors.length === 0) return null

  return (
    <p className="text-xs text-amber-500">
      Last run had errors in: {errors.join(', ')}
    </p>
  )
}
